export { ConfiguracionTemplate } from './ConfiguracionTemplate';
export { EquiposTemplate } from './EquiposTemplate';
export { EquipoesTemplate } from './EquiposTemplate copy';
export { HomeTemplate } from './HomeTemplate';
export { LoginTemplate } from './LoginTemplate';
export { MarcaTemplate } from './MarcaTemplate';
export { MarcasTemplate } from './MarcasTemplate';
export { MenuInventarioTemplate } from './MenuInventarioTemplate';
export { MenuMarcasTemplate } from './MenuMarcasTemplate';
export { ModelosTemplate } from './ModelosTemplate';
export { MonitoresTemplate } from './MonitoresTemplate';
export { PlantillaBase } from './PlantillaBase';
export { UsuariosTemplate } from './UsuariosTemplate';
