export { Configuracion } from './Configuracion';
export { Equipos } from './Equipos';
export { Eqeuipos } from './Equipos copy';
export { Home } from './Home';
export { Login } from './Login';
export { Marca } from './Marca';
export { Marcas } from './Marcas';
export { MenuInventario } from './MenuInventario';
export { MenuMarcas } from './MenuMarcas';
export { Modelos } from './Modelos';
export { Monitores } from './Monitores';
export { PageBase } from './PageBase';
export { Usuarios } from './Usuarios';
