export { useMarcasStore } from '../store/marcasStore';
export { DeleteCentros, EditCentros, InsertCentros, ShowCentros } from './centrosCrud';
export { DeleteDepartamentos, EditDepartamentos, InsertDepartamentos, ShowDepartamentos } from './departamentosCrud';
export { CountEquipos, DeleteEquipos, EditEquipos, InsertEquipos, ShowDepartamentoByEquipo, ShowEquipos, ShowEquiposByEstado, ShowEquiposByMarca, ShowEquiposByTipo, ShowEquiposComunes, ShowMonitores } from './equiposCrud';
export { ShowEstados } from './estadosCrud';
export { GetIdAuthSupabase } from './globalSupabase';
export { CountMarcas, DeleteMarcas, EditMarcas, InsertMarcas, SearchMarcas, ShowMarcas } from './marcasCrud';
export { CountModelos, DeleteModelos, EditModelos, InsertModelos, SearchModelos, ShowModelos, ShowModelosByMarca } from './modelosCrud';
export { ShowRoles } from './rolesCrud';
export { supabase } from './supabase.config';
export { CountTest, DeleteTest, EditTest, InsertTest, InsertWithIDTest, SearchTest, ShowTest } from './testCrud';
export { SearchTipos, ShowTipos } from './tiposCrud';
export { DeleteUser, EditUser, InsertUser, ShowAllUsers, ShowUsers } from './usersCrud';
